import PDFDocument from "pdfkit";
import * as path from "path";

const AMIRI_FONT_PATH = path.resolve(process.cwd(), "server/assets/fonts/Amiri-Regular.ttf");

export type PdfLocale = "ar" | "en" | "bilingual";

export interface CarInfo {
  make: string;
  makeAr: string;
  model: string;
  modelAr: string;
  year: string;
}

export interface PartEntry {
  id: string;
  name: string;
  nameAr: string;
  confidence: number;
  price: number;
}

// ── SSRF guard ────────────────────────────────────────────────────────────────

const PRIVATE_HOSTNAME_RE =
  /^(localhost|.*\.local)$|^127\.|^10\.|^192\.168\.|^172\.(1[6-9]|2\d|3[01])\.|^169\.254\.|^\[?::1\]?$|^\[?fc|^\[?fd/i;

function isSafeImageUri(uri: string): boolean {
  if (!uri.startsWith("https://")) return false;
  try {
    const { hostname } = new URL(uri);
    if (PRIVATE_HOSTNAME_RE.test(hostname)) return false;
    return true;
  } catch {
    return false;
  }
}

const MAX_IMAGE_BYTES = 10 * 1024 * 1024;

async function fetchImageBuffer(uri: string): Promise<Buffer | null> {
  if (!isSafeImageUri(uri)) {
    console.warn(`[analysisPdf] Image URI rejected by SSRF guard: ${uri.slice(0, 80)}`);
    return null;
  }
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 8000);
  try {
    const resp = await fetch(uri, { signal: controller.signal, redirect: "error" });
    if (!resp.ok) { console.warn(`[analysisPdf] Image fetch failed: HTTP ${resp.status}`); return null; }
    const contentType = resp.headers.get("content-type") ?? "";
    if (!contentType.startsWith("image/")) { console.warn(`[analysisPdf] Rejected non-image: ${contentType}`); return null; }
    const contentLength = parseInt(resp.headers.get("content-length") ?? "0", 10);
    if (contentLength > MAX_IMAGE_BYTES) { console.warn(`[analysisPdf] Image too large (header): ${contentLength}`); return null; }
    const arrayBuffer = await resp.arrayBuffer();
    if (arrayBuffer.byteLength > MAX_IMAGE_BYTES) { console.warn(`[analysisPdf] Image too large (body): ${arrayBuffer.byteLength}`); return null; }
    return Buffer.from(arrayBuffer);
  } catch (err: any) {
    console.warn(`[analysisPdf] Image fetch error: ${err?.message ?? err}`);
    return null;
  } finally {
    clearTimeout(timeoutId);
  }
}

// ── Label sets ────────────────────────────────────────────────────────────────

interface Labels {
  appName: string;
  reportTitle: string;
  dateLabel: string;
  vehicleInfo: string;
  makeLabel: string;
  modelLabel: string;
  yearLabel: string;
  damagePhoto: string;
  detectedParts: string;
  colName: string;
  colConfidence: string;
  colPrice: string;
  totalLabel: (amount: string) => string;
  footer: string;
  photoError: string;
}

const LABELS: Record<PdfLocale, Labels> = {
  ar: {
    appName: "لاقط",
    reportTitle: "تقرير تشخيص أضرار السيارة",
    dateLabel: "التاريخ",
    vehicleInfo: "معلومات السيارة",
    makeLabel: "الصنع",
    modelLabel: "الموديل",
    yearLabel: "السنة",
    damagePhoto: "صورة الضرر",
    detectedParts: "القطع المكتشفة",
    colName: "اسم القطعة",
    colConfidence: "الثقة",
    colPrice: "السعر التقديري (ريال)",
    totalLabel: (a) => `الإجمالي التقديري: ${a} ريال`,
    footer: "جميع الأسعار تقديرية — لاقط | laqit.app",
    photoError: "[تعذّر تضمين الصورة]",
  },
  en: {
    appName: "Laqit",
    reportTitle: "Car Damage Analysis Report",
    dateLabel: "Date",
    vehicleInfo: "Vehicle Information",
    makeLabel: "Make",
    modelLabel: "Model",
    yearLabel: "Year",
    damagePhoto: "Damage Photo",
    detectedParts: "Detected Parts",
    colName: "Part Name",
    colConfidence: "Confidence",
    colPrice: "Est. Price (SAR)",
    totalLabel: (a) => `Total Estimated: ${a} SAR`,
    footer: "Generated by Laqit | laqit.app — All prices are estimates only.",
    photoError: "[Photo could not be embedded]",
  },
  bilingual: {
    appName: "لاقط / Laqit",
    reportTitle: "تقرير تشخيص أضرار السيارة",
    dateLabel: "Date",
    vehicleInfo: "معلومات السيارة / Vehicle Information",
    makeLabel: "Make",
    modelLabel: "Model",
    yearLabel: "Year",
    damagePhoto: "صورة الضرر / Damage Photo",
    detectedParts: "القطع المكتشفة / Detected Parts",
    colName: "اسم القطعة",
    colConfidence: "Confidence",
    colPrice: "Est. Price (SAR)",
    totalLabel: (a) => `Total Estimated: ${a} SAR`,
    footer: "Generated by Laqit — لاقط | laqit.app — All prices are estimates only.",
    photoError: "[Photo could not be embedded]",
  },
};

// ── Main generator ────────────────────────────────────────────────────────────

export async function generateAnalysisPdf(
  carInfo: CarInfo,
  parts: PartEntry[],
  imageUri?: string,
  locale: PdfLocale = "ar"
): Promise<Buffer> {
  const imageBuffer = imageUri ? await fetchImageBuffer(imageUri) : null;
  const L = LABELS[locale];

  // Font helpers based on locale
  const isAr = locale === "ar";
  const defaultFont = isAr ? "Arabic" : "Helvetica";
  const boldFont = isAr ? "Arabic" : "Helvetica-Bold"; // Amiri Regular used for bold too until bold variant added
  const defaultAlign = isAr ? "right" : "left";

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.registerFont("Arabic", AMIRI_FONT_PATH);

    const blue = "#1E74F2";
    const gray = "#6B7280";
    const light = "#F3F4F6";
    const dark = "#111827";
    const pageWidth = doc.page.width - 100;

    // ── Header bar ────────────────────────────────────────────────────────────
    doc.rect(50, 40, pageWidth, 60).fill(blue);

    doc
      .font(defaultFont)
      .fontSize(locale === "bilingual" ? 14 : 18)
      .fillColor("#FFFFFF")
      .text(L.appName, 50, 55, { width: pageWidth, align: defaultAlign });

    doc.moveDown(3);

    // ── Report title & date ───────────────────────────────────────────────────
    const dateStr = new Date().toLocaleDateString(isAr ? "ar-SA" : "en-GB", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });

    // For bilingual: Arabic title on top, English subtitle below
    if (locale === "bilingual") {
      doc.font("Arabic").fontSize(14).fillColor(dark)
        .text("تقرير تشخيص أضرار السيارة", 50, 120, { width: pageWidth, align: "center" });
      doc.font("Helvetica").fontSize(11).fillColor(gray)
        .text("Car Damage Analysis Report", 50, 137, { width: pageWidth, align: "center" });
      doc.font("Helvetica").fontSize(9).fillColor(gray)
        .text(`Date: ${dateStr}`, 50, 152, { width: pageWidth, align: "center" });
    } else {
      doc.font(boldFont).fontSize(15).fillColor(dark)
        .text(L.reportTitle, 50, 122, { width: pageWidth, align: "center" });
      doc.font(defaultFont).fontSize(9).fillColor(gray)
        .text(`${L.dateLabel}: ${dateStr}`, 50, 142, { width: pageWidth, align: "center" });
    }

    // ── Divider ───────────────────────────────────────────────────────────────
    doc.moveDown(locale === "bilingual" ? 0.5 : 1.2);
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).strokeColor(blue).lineWidth(1.5).stroke();
    doc.moveDown(1);

    // ── Car info section ──────────────────────────────────────────────────────
    const carY = doc.y;
    doc.rect(50, carY, pageWidth, 28).fill(light);

    doc.font(boldFont).fontSize(12).fillColor(blue)
      .text(L.vehicleInfo, 50, carY + 8, { width: pageWidth, align: defaultAlign });

    doc.moveDown(0.3);

    const colW = pageWidth / 3;
    const labelY = doc.y + 4;
    const valueY = labelY + 14;

    // Column labels
    if (locale === "bilingual") {
      // English label row on top
      doc.font("Helvetica").fontSize(9).fillColor(gray)
        .text("Make", 50, labelY, { width: colW })
        .text("Model", 50 + colW, labelY, { width: colW })
        .text("Year", 50 + colW * 2, labelY, { width: colW });

      // Arabic make + English in parens
      doc.font("Arabic").fontSize(12).fillColor(dark)
        .text(carInfo.makeAr, 50, valueY, { width: colW, align: "left" });
      doc.font("Helvetica").fontSize(10).fillColor(gray)
        .text(`(${carInfo.make})`, 50, valueY + 14, { width: colW });

      doc.font("Arabic").fontSize(12).fillColor(dark)
        .text(carInfo.modelAr, 50 + colW, valueY, { width: colW, align: "left" });
      doc.font("Helvetica").fontSize(10).fillColor(gray)
        .text(`(${carInfo.model})`, 50 + colW, valueY + 14, { width: colW });

      doc.font("Helvetica-Bold").fontSize(13).fillColor(dark)
        .text(carInfo.year, 50 + colW * 2, valueY, { width: colW });
    } else if (isAr) {
      // Arabic: labels right-aligned, Arabic values
      doc.font("Arabic").fontSize(9).fillColor(gray)
        .text(L.makeLabel, 50, labelY, { width: colW, align: "right" })
        .text(L.modelLabel, 50 + colW, labelY, { width: colW, align: "right" })
        .text(L.yearLabel, 50 + colW * 2, labelY, { width: colW, align: "right" });

      doc.font("Arabic").fontSize(13).fillColor(dark)
        .text(carInfo.makeAr, 50, valueY, { width: colW, align: "right" });
      doc.font("Arabic").fontSize(13).fillColor(dark)
        .text(carInfo.modelAr, 50 + colW, valueY, { width: colW, align: "right" });
      doc.font("Helvetica-Bold").fontSize(13).fillColor(dark)
        .text(carInfo.year, 50 + colW * 2, valueY, { width: colW, align: "right" });
    } else {
      // English: standard LTR
      doc.font("Helvetica").fontSize(9).fillColor(gray)
        .text(L.makeLabel, 50, labelY, { width: colW })
        .text(L.modelLabel, 50 + colW, labelY, { width: colW })
        .text(L.yearLabel, 50 + colW * 2, labelY, { width: colW });

      doc.font("Helvetica-Bold").fontSize(12).fillColor(dark)
        .text(carInfo.make, 50, valueY, { width: colW });
      doc.font("Helvetica-Bold").fontSize(12).fillColor(dark)
        .text(carInfo.model, 50 + colW, valueY, { width: colW });
      doc.font("Helvetica-Bold").fontSize(13).fillColor(dark)
        .text(carInfo.year, 50 + colW * 2, valueY, { width: colW });
    }

    doc.moveDown(3.2);

    // ── Damage photo ──────────────────────────────────────────────────────────
    if (imageBuffer) {
      const imgSectionY = doc.y;
      doc.rect(50, imgSectionY, pageWidth, 28).fill(light);

      doc.font(boldFont).fontSize(12).fillColor(blue)
        .text(L.damagePhoto, 50, imgSectionY + 8, { width: pageWidth, align: defaultAlign });

      doc.moveDown(0.5);
      const maxImgHeight = 200;
      try {
        doc.image(imageBuffer, 50, doc.y, { fit: [pageWidth, maxImgHeight], align: "center", valign: "center" });
        doc.y = Math.max(doc.y, imgSectionY + 28 + maxImgHeight + 8);
      } catch (imgErr: any) {
        console.warn(`[analysisPdf] Could not embed image: ${imgErr?.message}`);
        doc.font(defaultFont).fontSize(10).fillColor(gray)
          .text(L.photoError, 50, doc.y, { width: pageWidth, align: "center" });
        doc.moveDown(1);
      }
    }

    doc.moveDown(0.5);

    // ── Parts table ───────────────────────────────────────────────────────────
    if (doc.y > doc.page.height - 150) doc.addPage();

    const tableY = doc.y;
    doc.rect(50, tableY, pageWidth, 28).fill(blue);
    doc.font(boldFont).fontSize(12).fillColor("#FFFFFF")
      .text(L.detectedParts, 50, tableY + 8, { width: pageWidth, align: defaultAlign });

    let rowTop = tableY + 28 + 5;

    if (locale === "bilingual") {
      // 4-column layout: Arabic name | English name | Confidence | Price
      const c1 = 50;
      const c2 = 50 + pageWidth * 0.36;
      const c3 = 50 + pageWidth * 0.63;
      const c4 = 50 + pageWidth * 0.78;

      doc.font("Helvetica-Bold").fontSize(8).fillColor(gray)
        .text("Arabic Name", c1, rowTop, { width: pageWidth * 0.34 })
        .text("English Name", c2, rowTop, { width: pageWidth * 0.25 })
        .text("Confidence", c3, rowTop, { width: pageWidth * 0.14 })
        .text("Est. Price (SAR)", c4, rowTop, { width: pageWidth * 0.22 });

      rowTop += 18;
      doc.moveTo(50, rowTop).lineTo(50 + pageWidth, rowTop).strokeColor("#E5E7EB").lineWidth(0.5).stroke();

      parts.forEach((part, i) => {
        if (rowTop > doc.page.height - 100) { doc.addPage(); rowTop = 60; }
        if (i % 2 === 0) doc.rect(50, rowTop, pageWidth, 24).fill(light);
        const confColor = part.confidence >= 90 ? "#16A34A" : part.confidence >= 75 ? "#22C55E" : part.confidence >= 60 ? "#D97706" : "#DC2626";

        doc.font("Arabic").fontSize(10).fillColor(dark)
          .text(part.nameAr, c1, rowTop + 6, { width: pageWidth * 0.34, align: "right" });
        doc.font("Helvetica").fontSize(9).fillColor(dark)
          .text(part.name, c2, rowTop + 8, { width: pageWidth * 0.25 });
        doc.font("Helvetica-Bold").fontSize(9).fillColor(confColor)
          .text(`${part.confidence}%`, c3, rowTop + 8, { width: pageWidth * 0.14 });
        doc.font("Helvetica").fontSize(9).fillColor(dark)
          .text(`${part.price.toLocaleString()} SAR`, c4, rowTop + 8, { width: pageWidth * 0.22 });

        rowTop += 24;
        doc.moveTo(50, rowTop).lineTo(50 + pageWidth, rowTop).strokeColor("#E5E7EB").lineWidth(0.3).stroke();
      });
    } else if (isAr) {
      // 3-column Arabic layout: part name | confidence | price — all right-aligned
      const cName = 50;
      const cConf = 50 + pageWidth * 0.62;
      const cPrice = 50 + pageWidth * 0.78;
      const nameW = pageWidth * 0.60;
      const confW = pageWidth * 0.14;
      const priceW = pageWidth * 0.22;

      doc.font("Arabic").fontSize(9).fillColor(gray)
        .text(L.colPrice, cPrice, rowTop, { width: priceW, align: "right" })
        .text(L.colConfidence, cConf, rowTop, { width: confW, align: "right" })
        .text(L.colName, cName, rowTop, { width: nameW, align: "right" });

      rowTop += 18;
      doc.moveTo(50, rowTop).lineTo(50 + pageWidth, rowTop).strokeColor("#E5E7EB").lineWidth(0.5).stroke();

      parts.forEach((part, i) => {
        if (rowTop > doc.page.height - 100) { doc.addPage(); rowTop = 60; }
        if (i % 2 === 0) doc.rect(50, rowTop, pageWidth, 24).fill(light);
        const confColor = part.confidence >= 90 ? "#16A34A" : part.confidence >= 75 ? "#22C55E" : part.confidence >= 60 ? "#D97706" : "#DC2626";

        doc.font("Arabic").fontSize(10).fillColor(dark)
          .text(part.nameAr, cName, rowTop + 6, { width: nameW, align: "right" });
        doc.font("Helvetica-Bold").fontSize(9).fillColor(confColor)
          .text(`${part.confidence}%`, cConf, rowTop + 8, { width: confW, align: "right" });
        doc.font("Helvetica").fontSize(9).fillColor(dark)
          .text(`${part.price.toLocaleString()}`, cPrice, rowTop + 8, { width: priceW, align: "right" });

        rowTop += 24;
        doc.moveTo(50, rowTop).lineTo(50 + pageWidth, rowTop).strokeColor("#E5E7EB").lineWidth(0.3).stroke();
      });
    } else {
      // 3-column English layout: part name | confidence | price — LTR
      const cName = 50;
      const cConf = 50 + pageWidth * 0.62;
      const cPrice = 50 + pageWidth * 0.78;
      const nameW = pageWidth * 0.60;
      const confW = pageWidth * 0.14;
      const priceW = pageWidth * 0.22;

      doc.font("Helvetica-Bold").fontSize(8).fillColor(gray)
        .text(L.colName, cName, rowTop, { width: nameW })
        .text(L.colConfidence, cConf, rowTop, { width: confW })
        .text(L.colPrice, cPrice, rowTop, { width: priceW });

      rowTop += 18;
      doc.moveTo(50, rowTop).lineTo(50 + pageWidth, rowTop).strokeColor("#E5E7EB").lineWidth(0.5).stroke();

      parts.forEach((part, i) => {
        if (rowTop > doc.page.height - 100) { doc.addPage(); rowTop = 60; }
        if (i % 2 === 0) doc.rect(50, rowTop, pageWidth, 24).fill(light);
        const confColor = part.confidence >= 90 ? "#16A34A" : part.confidence >= 75 ? "#22C55E" : part.confidence >= 60 ? "#D97706" : "#DC2626";

        doc.font("Helvetica").fontSize(9).fillColor(dark)
          .text(part.name, cName, rowTop + 8, { width: nameW });
        doc.font("Helvetica-Bold").fontSize(9).fillColor(confColor)
          .text(`${part.confidence}%`, cConf, rowTop + 8, { width: confW });
        doc.font("Helvetica").fontSize(9).fillColor(dark)
          .text(`${part.price.toLocaleString()} SAR`, cPrice, rowTop + 8, { width: priceW });

        rowTop += 24;
        doc.moveTo(50, rowTop).lineTo(50 + pageWidth, rowTop).strokeColor("#E5E7EB").lineWidth(0.3).stroke();
      });
    }

    // ── Total ─────────────────────────────────────────────────────────────────
    const total = parts.reduce((sum, p) => sum + p.price, 0);
    doc.y = rowTop + 8;
    doc.moveTo(50, doc.y).lineTo(50 + pageWidth, doc.y).strokeColor(blue).lineWidth(1).stroke();
    doc.moveDown(0.5);

    const totalStr = total.toLocaleString();
    doc.font(isAr ? "Arabic" : "Helvetica-Bold").fontSize(12).fillColor(dark)
      .text(L.totalLabel(totalStr), 50, doc.y, { width: pageWidth, align: defaultAlign });

    if (locale === "bilingual") {
      doc.font("Arabic").fontSize(12).fillColor(dark)
        .text(`الإجمالي التقديري: ${totalStr} ريال`, 50, doc.y - 16, { width: pageWidth, align: "right" });
    }

    // ── Footer ────────────────────────────────────────────────────────────────
    const footerY = doc.page.height - 48;
    doc.font(isAr ? "Arabic" : "Helvetica").fontSize(8).fillColor(gray)
      .text(L.footer, 50, footerY, { width: pageWidth, align: "center" });

    doc.end();
  });
}
